---
Name: clippy_config
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'silverstripe/clippy: client/dist/styles/styles.css'
  help_links:
    # Add a new link
    'Bespoke CMS User Guide': '/cms-user-guide'
  extensions:
    - SilverStripe\Clippy\Extension\DocumentationPageLeftAndMain

SilverStripe\Clippy\PageTypes\DocumentationPage:
  default_url_segment: cms-user-guide
  extensions:
    - SilverStripe\Clippy\Extension\DocumentationPageMetaTagsExtension

SilverStripe\Clippy\Controllers\DocumentationPageController:
  docs_dir: /docs/userguides
  allowed_extensions:
    - md

SilverStripe\CMS\Controllers\CMSMain:
  extensions:
    - SilverStripe\Clippy\Extension\CMSMainExtension

# Hide the documentation page from CMS site tree and frontend heirarchies
SilverStripe\ORM\Hierarchy\Hierarchy:
  hide_from_hierarchy:
    - SilverStripe\Clippy\PageTypes\DocumentationPage

SilverStripe\CMS\Model\SiteTree:
  extensions:
    - SilverStripe\Clippy\Extension\SiteTreePreviewLinkExtension
